/* DO NOT EDIT: This file is automatically generated by Gtk2HsSetup.hs */

/* package cairo-1.10.2 */
#define VERSION_cairo "1.10.2"
#define MIN_VERSION_cairo(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  10 || \
  (major1) == 1 && (major2) == 10 && (minor) <= 2)

/* package pangocairo-1.29.4 */
#define VERSION_pangocairo "1.29.4"
#define MIN_VERSION_pangocairo(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  29 || \
  (major1) == 1 && (major2) == 29 && (minor) <= 4)

/* package pango-1.29.4 */
#define VERSION_pango "1.29.4"
#define MIN_VERSION_pango(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  29 || \
  (major1) == 1 && (major2) == 29 && (minor) <= 4)

