/* DO NOT EDIT: This file is automatically generated by Gtk2HsSetup.hs */

/* package glib-2.0-2.48.0 */
#define VERSION_glib_2_0 "2.48.0"
#define MIN_VERSION_glib_2_0(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  48 || \
  (major1) == 2 && (major2) == 48 && (minor) <= 0)

/* package gobject-2.0-2.48.0 */
#define VERSION_gobject_2_0 "2.48.0"
#define MIN_VERSION_gobject_2_0(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  48 || \
  (major1) == 2 && (major2) == 48 && (minor) <= 0)

