/* DO NOT EDIT: This file is automatically generated by Gtk2HsSetup.hs */

/* package gthread-2.0-2.48.0 */
#define VERSION_gthread_2_0 "2.48.0"
#define MIN_VERSION_gthread_2_0(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  48 || \
  (major1) == 2 && (major2) == 48 && (minor) <= 0)

/* package gtk+-2.0-2.24.28 */
#define VERSION_gtk+_2_0 "2.24.28"
#define MIN_VERSION_gtk+_2_0(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 28)

