/* DO NOT EDIT: This file is automatically generated by Gtk2HsSetup.hs */

/* package gthread-2.0-2.28.8 */
#define VERSION_gthread_2_0 "2.28.8"
#define MIN_VERSION_gthread_2_0(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  28 || \
  (major1) == 2 && (major2) == 28 && (minor) <= 8)

/* package gtk+-2.0-2.24.10 */
#define VERSION_gtk+_2_0 "2.24.10"
#define MIN_VERSION_gtk+_2_0(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 10)

