/* DO NOT EDIT: This file is automatically generated by Gtk2HsSetup.hs */

/* package gio-2.0-2.28.8 */
#define VERSION_gio_2_0 "2.28.8"
#define MIN_VERSION_gio_2_0(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  28 || \
  (major1) == 2 && (major2) == 28 && (minor) <= 8)

